openapi: 3.1.0
info:
  version: '1.0'
  title: mfimporter-api
  summary: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /imports:
    get:
      summary: Your GET endpoint
      operationId: get-imports
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Import'
      servers:
        - url: 'http://localhost:3000'
components:
  responses:
    import:
      description: /import response
      content:
        application/json:
          schema:
            type: object
            properties:
              useDate:
                type: string
                format: date
                examples:
                  - '2024-06-01'
              name:
                type: string
              registDate:
                type: string
                format: date-time
                examples:
                  - '2024-06-03 15:00:00'
              importJudgeDate:
                type: string
                format: date-time
              importDate:
                type: string
                format: date-time
                examples:
                  - '2024-06-03 15:00:00'
            required:
              - useDate
              - name
              - registDate
              - importJudgeDate
            examples:
              - '2024-06-01'
          examples:
            default:
              value: '2024-06-01'
  schemas:
    Import:
      type: object
      title: Import
      properties:
        id:
          type: number
        useDate:
          type: string
          format: date
        name:
          type: string
        registDate:
          type: string
          format: date-time
        importJudgeDate:
          type: string
          format: date-time
        importDate:
          type: string
          format: date-time
      required:
        - id
        - useDate
        - name
        - registDate
