openapi: 3.1.0
info:
  version: '1.0'
  title: mfimporter-api
  summary: ''
servers:
  - url: 'http://localhost:3000'
paths:
  /details:
    get:
      summary: get details
      operationId: get-details
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Detail'
      servers:
        - url: 'http://localhost:3000'
  /health:
    get:
      summary: health check
      operationId: get-health
      requestBody:
        content:
          text/plain:
            schema:
              type: string
              default: OK
              examples:
                - OK
            examples:
              default:
                value: OK
      responses: {}
      servers:
        - url: 'http://localhost:3000'
  '/details/{id}':
    get:
      summary: '[WIP] get detail'
      operationId: get-details-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Detail'
      servers:
        - url: 'http://localhost:3000'
    patch:
      summary: '[WIP] change status detail'
      operationId: patch-details-id
      parameters:
        - name: ope
          in: query
          description: 'operate name ("reset": judge history reset)'
          required: true
          schema:
            type: string
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content: {}
      responses:
        '200':
          description: OK
        '400':
          description: "Bad Request\r\nUnknown operate name"
      servers:
        - url: 'http://localhost:3000'
      x-internal: false
    delete:
      summary: '[WIP] delete detail'
      operationId: delete-details-id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No Content
      servers:
        - url: 'http://localhost:3000'
  /histories:
    get:
      summary: '[WIP] get import hisories'
      operationId: get-histories
      responses: {}
      servers:
        - url: 'http://localhost:3000'
components:
  responses:
    import:
      description: /import response
      content:
        application/json:
          schema:
            type: object
            properties:
              useDate:
                type: string
                format: date
                examples:
                  - '2024-06-01'
              name:
                type: string
              registDate:
                type: string
                format: date-time
                examples:
                  - '2024-06-03 15:00:00'
              importJudgeDate:
                type: string
                format: date-time
              importDate:
                type: string
                format: date-time
                examples:
                  - '2024-06-03 15:00:00'
            required:
              - useDate
              - name
              - registDate
              - importJudgeDate
            examples:
              - '2024-06-01'
          examples:
            default:
              value: '2024-06-01'
  schemas:
    Detail:
      type: object
      title: Import
      properties:
        id:
          type: integer
        useDate:
          type: string
          format: date
        name:
          type: string
        price:
          type: integer
        registDate:
          type: string
          format: date-time
        importJudgeDate:
          type: string
          format: date-time
        importDate:
          type: string
          format: date-time
      required:
        - id
        - useDate
        - name
        - price
        - registDate
