// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1FvdbxzJcf9XChMDJ+WWu9THPZhEYOjTRyuWBOkCP0jKoXemdrdPM92j7h6KK5JA6IfkjAROYCP2IbBx",
	"T8kdEPiSAH4wEMP3x/Ak20/+F4yq7vnamV0uSUm+eyN7+qO6Pn9VXbsfxTrLtULlbLS1H+XCiAwdGv7v",
	"oS5MjPxngjY2MndSq2greoA5CifGKYLlOTCRqUMzhHuZdOA0GHxWoHUw1m4W5thhNIhwL091gtGWMwUO",
	"Ikm7PSvQzKNBpESG0VbkZ0eDyMYzzIQ/fSKK1EVbjyI7ljTVPFXRk0EkHWZMH6oi635285x3dEaqaXQ4",
	"iDKpdvySS9VXYYyg4wslnxUYPhN5h4PIunlKcybaZNHh4SAyaHOtrGfKdZE88Pek/2KtHCr+U+R5KmNB",
	"3Bp9ZIll+43bfMvgJNqK/mpU837kv9rRtVzeMkab6JBOa3N9R+2KVCZQCQm0AaloF+HkOMWRDDPiwlht",
	"hnTju9rd1oVK3gqFD5XI7Uw72LkJiUYLSjvAPWldSctOlqeYoXKYdNXqlkpyLZUDacHmGMuJxATGheN9",
	"ZL0UxnNwM5qFZhcN7KKxUqshiygQSttXtJJqG52jcdKLDsvhBRVhET8rpCH6HoVptSbp8UcYO7rLdZEK",
	"FeN9McXuRa6lz8XcgkFXGGWBtRSESkAVacpmo3DP3fBSgodSTVOETCdYrgHcE7FL56AV8vJtMEJN/STA",
	"TDrLnzy7ciQ9IKvF2Ek1hVikqBJh6IvUyYC0JC0S+uRHLDyXbgZKQyKcgAtEFzjtROrpzKS1Uk2DA7i4",
	"DYJImonCEvdzQZSIOYyJltzNh437kPB4O6nA1jfjbbUCNyNnoUQaLkR7DSEcBKShQipb3Z+mB1+CSeVI",
	"FuiDVFpmSDovp1T3w1ROJTuqoJsDVqZq2kxbBKkSuSuTQqSQoTMytiAM8jWG4K9lgUxm7g8hB1eLg25G",
	"03UunhU4ABvrHBOaFE4ZwMTobABOD7ycdkXKq1KZSbcNBm2RunCmdjT7BSoYo3uOqJhF7DzbKlz5vuqP",
	"VWZb6ispDOlvy/kdDqJagCftdDfo8MN+k/HUtDZcZT9MT9cTNNSfeSwt5DovUuEwaVkMFBYtOJmhdSLL",
	"KysLiv7QCeNG/u9bKmmZEa/0mt9azjGrd3nr5Heax0rbUFPhBuSa48IYVI5nwfMZKtCZdHyBB0zFrkgL",
	"tEQHTNDFM0yuOSBPxHcf40QbhAbtYX4sjJnDRJvnwiSsWuVcthbaegj3g52zYpoEjfeajWt1NaptVWur",
	"lp/fp1QV7evq1E3hsF7IZJ52qT0l9UERl1+iEvJpKPlAZn4z9qkccdP03iTaerR6jw/8/MMnBJUERTwf",
	"uK37Xj6PtkhbCakYFKl8gcl9lTbGST84pPNYdOnyleHV93ycblpofaE2o5vyqiivGTpY1I8VZh242bHr",
	"H5AV9HlljxLsoBrYSdgWa7soHbJ3t3W4mkhMk6a/rpdI682OzCLgVA53z4UtZ3WNoFp+FnHX1J/Wi5Z8",
	"PoWxVaq1jkIt6EANsmuKB427V9v3CfkmxjITaSC9I+TwGVSRjdEAqlgn5BUtCPA4awi3vHJ7uc2ESjae",
	"G/KNCuxcuRk6GQd357OGYArRpc3N4eYmCU04h4aO+/uN7zza3Pj2k3cvPH489H9d/M63oh70fxOdkGkX",
	"DMqkgQQpQE/R0HyZ5do4diykGNpkwkVbUSIcbpAR9Z3h13yvSKZ4uoU++9nvfsiNjLGfQINTaU9JYGH7",
	"CevOXQzspCHl6kBvSV2LFFIZ6VhcO8yNqFeHSBb2hi58/G9LJC6H25rFOlnqlZ5A4jep9694s0C7369P",
	"l9/XadKrxTP/YSfhbMQnuwz+CFlKBQTBZZYVIQ0OZjSEXFtJW9zBOa0UNea3zYz5XcbqWr2bG50UsYOn",
	"OAcRG21ttRm7L4MgE1ROTiQt34bbO9/dYZCtHUEHNixetxF8XKA8LCN0/n3vuEeFErtCemoCmCj95ja5",
	"5cbYtEBLm2sDCRq5S6ilGV8gE7n1Cz78KJ+zV16MS35OrlKeIVW7GgAhqvlZdx/cucsjNHcbHl7fqb6H",
	"hGIIBidoUMWsgo1l1fiHpMhMSpmETLShvYYQ2O1X0e7lwOJs2nEIQSo3CCfWB4XRD+MS9neOaUqf8eWC",
	"tFl4YbYPTjxSRj/tZmieS1vKhE9t7tOgawh3cG4bmQdlHHEqyf13wxqHBisd3pZTefrgVCGQNWOiDwG0",
	"srKjXue23OvVjDw9tQ0unX7xs0Kw2Zzhri0FPTVw9SpyeoK7cPDUhLeR4ymXL/jaWuBtKdY3bAtosKCb",
	"i2ysQk0lmAV6a+3s4UWfz29xnqC5mgdofkJEHFSKSubJKH1vY6o3wuBfh3mN0Q37VOYbmoOKSDe4XoOm",
	"qi92MORyapYF9DdGUhBvi6JVetFGhX2E9cC410NrjURrUt80nx4UPjdbcLPC4VSbuXd34cI22np0+dLm",
	"k0EPhONC1/eFi2ecgYs9mRUZl6czqfzfm33rOO25G7xn4xxvLH2172Uol2P4yaVQhn/1qeW6QfPKres0",
	"YOCtPWdE7JhlPfZI441C+iqO/iUZuCajzs+jkhc9rCor7HUqs15doVz3sMgyYeZsD20+B7e9fuGkRM6d",
	"kkl/POhLJZ80blRW0s9T5FzgztegzLnI906a4fP5qvZuEAzmBq1/5xAWkpBNe22z2x5wZiiUhQaeP6GQ",
	"0T6UQs2qishpUt0VJ/gnmrLCQ2eUS0Aqp31dZm4dZusf2q6wLPAyZGkeDU9TPRZpOgf/sAc7Nxl4M1E9",
	"iVvvYW+1JNOsxFT1mWZJpsHwlfWZuvq25rPoBxXdbYZ2Ez5KW6ZGqORDPp8Tu5FPUxaG6/xuWWro02le",
	"61eV6R+vCGmjTwUXktUhXJtODU4p20MRz3wREKRKMEdFaW/qNwmvaf49agJCzTuvSZCK+KkFNxMuPP4M",
	"4S7u8pPaBA2I8rHJE9EqRzUqs9GlywHSdOF4tFF+W6zQehh02E3Wzpptfc1ygfPgdNpLqonmiBuCZDYJ",
	"NmA2RE4qHV5+iZdDZqTOUdGnrejKkIa4Ujhjro7KctHWfjRFdlrEdKaP3En0XQyRw/KyuhXi0X5vpwI/",
	"37UaFbplqP6VejKx6Pp7HDYHvdu0LdNq40tGF0JF7oB2PuBq3EFdiztYKEce1CXNi9Gy9guzhLBG8a+D",
	"gHrp43cnuCBsfEBfl53I05YcSet6znuy0IlxeXPzVA0Oa6GJZSii2/fg+w64F8FrS2HSaCuaOZdvjUap",
	"jkU609ZtXdkka38yiGwJB0gRqzIm7VIq6agqgZ6gqr6Cek5+nMyGcE7P5e/deT3X90EA4nBOgxX7Mjn0",
	"apGiz9jbzLjJ44FOX3foMV7yA7XScTpTuyrfjrTCkLsad7UbL+9quBFYfnaWPPrBzv0n4O8aeEM6eIIa",
	"vLVrv27Feu0q5flXKxaH1zI/bLPvPg2vYGCbKr8WgVgJFx4TY9A9jrbgI3KvMJPWaUMAw6Jb6utyXEcA",
	"Tcf6uqTIsOe6TuZtAXa62oKIuxIZRFf7Pl0XCYSM9bF5rP5OPVX6uYImt84hzXjGrRLWCVfYUqKDaG+D",
	"qzFKpNHWRKQW2WFMpBIqliLdENais6Oxf45uhvyFB+nQJsQ9GrX0B1XvFuUoZSNHaGcKmw6BFwtXT9aq",
	"VAMZi7ScCAXDRwaqHnO+YyEVDq2rs6P61fpxsbl5Jf4bEC6cwB0ehGadro9KhEznoA1kWrlZOvetYBY0",
	"IddH3G/k9EWQCq5ZKUYf6Kdzve0fYCi/KlNNr0L+qZ2OyQrrIDcYY0JJadlHAmNdqEQYGRbGqcxDj1O7",
	"Q8u319B29SMW7zkTu6u6XJg5vv0AUCXDuk/qQgADkIj5xYFvmeIDfJMjk+O7HjmdkKrR4jME4SAWSmkH",
	"Y4RYZ2OpMPHNYXTfkdPb5R9LJ5aklIf71h46u1ApWuu56k+teZsbvSsTTIZwi+5GiANmwrY6+/Sk0UJ0",
	"odEtd5EO6W1Bggv19S4OPIEkAn45KpshfI7U7Rf192L/V3UaXt3cHMJD9h0QWG05Ue52qjVb4Fp83gbN",
	"SZJWi11/0nrhNDK2Oo3zD2Cik5KNfB5GixsVju3+rr8TG/6GcFcHbEGZPyV1xpc5OrH0duk/rpH7uF46",
	"j05c6Itq9ZRR2SDThcUPbt+AK1eufNs3ZFq5S87F6clkG7LCFVyuwL3yU1NNh0sCimiD9XWKKF2ydmpq",
	"ys5Rfkld8B7BXRBSW0YOUbucoHVoubV3OlroxGXUOH0+Wh7UzYKk9Nvkgyqfu+zQ0m6WZTTcbF4WZvx/",
	"vF9PZWYNirgX18oX6N1sRojG2xWFeKkKCj2i6ggfrJnIVvRe2twc1FX19/i/sq5+aZ1MtUNxKM8FF8pR",
	"hxxYbnBX6sL6juAlhPpF0SrE9CYRa7Ppuwe2hs+Nfu9QYqJYgORasIGi+g6qKB81fltwOIje27x08pKF",
	"9vqzY65XX/zzH//7k+Oj3x0ffXp89D+vfvHpH3/201c//vz3n/3/8Q9/8vJff/bydz+P+gFXFfWXIq52",
	"NOQSMOFp60wRu8IghFEP9QgMMLJp9rBn6EQinBg0W9ZFmpadLxbGmGo1pbmMUIRrRIP7YhpioM81G/02",
	"vje83GUbRPXpHVtvzuGLK4TOFCoWzrfJ2DylEOlbeHzPNjysQBAtqqvOYkLh2BdjhnDDN22AnekiTcAZ",
	"ET8lnYl9C46tf1Vhh3AvPEhWsMViinETQEoVACA4fXG7F9d5D8G4xf88A25luZtXnegBGwjl+/tLjTZG",
	"zIdwzyRouMHIgrAxKhbKeN4gwdH2dUG70URfd6uQ0BrArUIyXh3YcOrGeV8SLn3dNk2cQ6JDuzzii9D8",
	"zPSDRTfwGFGrErx7Zlv+3YKYTIhlhMFN3V7fhgN/K+0CHqiE+RoBQR15a+YFrD0fQAUXPHNkhi+0wrPF",
	"3rXBQB2Az0/SqgC8gqC3HaPutUKSV/7yV0bfjMjUekVd9cusnCd8A4LQV1/+8uWvPnn1m4+Pj748PvrC",
	"R52X//efr3716+Mf/uSr3/zDH/7rs+Ojz/z4n3778ct/+/gPn398fPT5V1/+8tUvfvTy3//x5U+PXn3y",
	"49//+n//9NsfnRSuRvu1tzpcVXXtdwlr1d5aD3zrl4DehtosL8VVisP2Xr3ln02Drvqi6Yka5H+x+PZx",
	"z7/808sv/uP46OfHR5+29O3oixXatQCJZihSN1ulQu/7GStqcpHDPTfKUyFVuzul4fT2y36Uqlrak2zc",
	"u1M/V3Jzy707fWnGYg3wzBz0l4d4hvHTwA5fDsOVr27vV5NeEx11DdiHfZhJ6w9gokyRriboAU84oR5c",
	"v8HJ5KDq+jlgsRzUTT4HdfPPGd7cuNT71p7bxF/utY2bw9Z4azv3cxMlCuibrcArgm837tGE+9pWqrDc",
	"WM/ufpvNXl0rjC577/fajupj5w2D4nxeUyRJi58NE1vz5Y5Z/CYfsNZ/+nhTj3rhOc8EJV/pd76BT3nL",
	"tOvcxmqqjdff4/DPAQAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
