// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RW32/bNhD+V4TbHjZAqZ20T3psMmxZsTYIMOwh8QMrnSymFMmQp86G4f99IClZUsU4",
	"bux26IthkDre3fd992MDuaq1kijJQrYBm1dYM//3Colx4f5pozQa4ujPeeF+aa0RMuCScIkGtinwWitD",
	"V4zQ3ZfK1Iwgg4IRnhGvEdLOyJLhctnb/NkUS/w6Q8lqHITRX2jDc4wHaHDJ7VcG2Nh4YNNvvYPHhhss",
	"ILtzKPXWbbxddKNQFikQJ+GeuvZo9E+rjw+YkwsjcGEvVSNpykjeHRdoc8M1cSUhA1LERCKb+iOaRJVJ",
	"ER7p399h80Xs4b1FJI7bRmDEPyNcKrO+9srAFau1cDd3F+fzRRphAlcsp78Y5ZUzqNmK100N2XkKNZfh",
	"/zxmV3IUxfuW+oGfAO8iJrAnxPqZiSYmoBiLvdfOLh2mPEpnwOZvKzIsJw/ZE1De4mODlp5D9P8E8ECg",
	"jseow2IClXPFZal8e2rqmpk1ZAD9I3UZ2giaM6a5CwCNDSVw/mruklAapbvK4PUrd5SCZlR5pGddVWQb",
	"WKKnwhHBXA059OF3pKtd4WhmWI2ExoG2Ae58PDZo1l2JZyB4zV0WoZPG6NumcUtVlhbHpgWWrBEUZXO7",
	"cBRYraQNormYz0M3kIShHzCtBc99LrMH6xDZDB7nhLU3/NlgCRn8NOtnwawdBLN2Cmx3/pkxbB1YGbcb",
	"rwmL5nOHTmMEZFAR6Ww2EypnolKWstfz+Rxc8D2ZS6Rdd3KvdKTMdp3tGWpCYzwSj+dhaP1Ekv/w7jTp",
	"J6Fp562fARQbXmyDJASGgTQG48qft3H6kouJ1em+V5xvb30Zk2lwr3CninszHTvvVXLZQv5ySO7+ub5Z",
	"JCHXFhunwWdk8N3SPrWwTi6pgF8vLL8adfNiDN+NO94D4DiqYIuJgzL55d4Bg3QPWfLglrik4paUWSf+",
	"+FdI441O4yEE9KPmdCz6GfNWFesxgWGcTSmeMpLCm9jVW1Yk7QS7N/fyb/lJqn9lMkTrCDbzisklJpYY",
	"NbZjNIXVmcvOSCYgK5mw6BtGhUxQta9p/hG+2IMHEK5opgXjcrwpDEbSptsNdkqdji13lY4WjQ/vImvG",
	"9kv8X4xUSD7JK8w/hf4ZFNnuVU8isvvoRHH09Rd2E1cYwYEPyjRif0C3/oPvMeD9fnrAeD96wjEhEgz7",
	"XhLydz1J2QgAN8oOEHhKoy9vusN9cyo+uJifn9RVDM5Lg4ywOAJTVhQjPAfKOnBZ8BB/y5l5eLf9VntE",
	"u0GYVuR7y+0H3B6eUtfRxWp2Dx/+xva/AAAA///2wKhhTRIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
