// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xSS2/TQBD+K9XA0a0Nve0RFZXCgQsXFOWw2JN4qn11dhw1ivLf0ewmcaARUiQu9mrn",
	"sd9rB330KQYMksHsIPcjeluODyiWnJ4Sx4QshOWeBv3KNiEYoCC4RoZ9A+RTZHmwglpfRfZWwMBgBW+F",
	"PEJzHMrCFNbzzNdpWON1g8F6PIMxFxJTj5cBMq4pXwlwypeBve0tD7xMxDiAWahK8/QB7xHdH1CWDQiJ",
	"01VPRY15dfz1jL3AXndTWMVi0OS95S0YgHnQr6qQyLc2ETSwQc4UAxj4cNcpj5gwaMnA/Z1eNZCsjMXP",
	"dihGl/MaRX9qtxWK4WkAA48oD4cWHWPrUZAzmMUOSN94mZC3R5IGHHlSFjVLl7zYL1WCnGLINVMfu05/",
	"fQyCoUCwKTnqC4j2OSuV3dlCEvRl8D3jCgy8a+cYt4cMt4cA7096Wma7rXIOmHumJFWk4l5G3hxpTezA",
	"wCiSTNu62Fs3xizmvus6UPCzCz/jxDePn3/cYBhSpCBlVzuidTL+S9IvtaOmBrN8isP2Lw0EX6VNzlJh",
	"j6/WJ1f1GnBlJ1eaNtZNSu77t8ripNGpR0vN2fhCL5ZvA1wjPLvyXzW5atn+dwAAAP//8K/wFZcEAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
