// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for Source.
const (
	SourceNrkn Source = "nrkn"
	SourceSbi  Source = "sbi"
)

// Valid indicates whether the value is a known member of the Source enum.
func (e Source) Valid() bool {
	switch e {
	case SourceNrkn:
		return true
	case SourceSbi:
		return true
	default:
		return false
	}
}

// Defines values for GetFinancialAssetBalancesParamsSource.
const (
	GetFinancialAssetBalancesParamsSourceNrkn GetFinancialAssetBalancesParamsSource = "nrkn"
	GetFinancialAssetBalancesParamsSourceSbi  GetFinancialAssetBalancesParamsSource = "sbi"
)

// Valid indicates whether the value is a known member of the GetFinancialAssetBalancesParamsSource enum.
func (e GetFinancialAssetBalancesParamsSource) Valid() bool {
	switch e {
	case GetFinancialAssetBalancesParamsSourceNrkn:
		return true
	case GetFinancialAssetBalancesParamsSourceSbi:
		return true
	default:
		return false
	}
}

// Defines values for GetFinancialAssetBalancesParamsInterval.
const (
	Day   GetFinancialAssetBalancesParamsInterval = "day"
	Month GetFinancialAssetBalancesParamsInterval = "month"
)

// Valid indicates whether the value is a known member of the GetFinancialAssetBalancesParamsInterval enum.
func (e GetFinancialAssetBalancesParamsInterval) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	default:
		return false
	}
}

// Defines values for ListFinancialAssetSnapshotsParamsSource.
const (
	ListFinancialAssetSnapshotsParamsSourceNrkn ListFinancialAssetSnapshotsParamsSource = "nrkn"
	ListFinancialAssetSnapshotsParamsSourceSbi  ListFinancialAssetSnapshotsParamsSource = "sbi"
)

// Valid indicates whether the value is a known member of the ListFinancialAssetSnapshotsParamsSource enum.
func (e ListFinancialAssetSnapshotsParamsSource) Valid() bool {
	switch e {
	case ListFinancialAssetSnapshotsParamsSourceNrkn:
		return true
	case ListFinancialAssetSnapshotsParamsSourceSbi:
		return true
	default:
		return false
	}
}

// ApiError defines model for ApiError.
type ApiError struct {
	Error string `json:"error"`
}

// BalancePage Always returns items and nullable nextCursor. Single modes return exactly one item; range mode emits one point per intersecting calendar period, including periods with no data (null totals and missingSources); an exhausted page may be empty. nextCursor is null in single mode and on the final range page. Sources contains exactly the requested sources. missingSources lists only sources with no eligible snapshot, not sources whose individual metrics are null. Cursors apply only to range mode and are opaque, scoped to sources, from, to, interval and limit; results are not frozen between pages.
type BalancePage struct {
	Items      []BalancePoint `json:"items"`
	NextCursor NullableString `json:"nextCursor"`
}

// BalancePoint Exactly one mode is populated. Single mode uses timestamp and null periodStart/periodEnd; range mode uses null timestamp and both periodStart/periodEnd. Single mode's timestamp is requested at, or current time when omitted. Range values use fetchedAt strictly before periodEnd; values carry forward from before the range. Periods are ordered by periodStart.
type BalancePoint struct {
	MissingSources []Source         `json:"missingSources"`
	PeriodEnd      NullableDate     `json:"periodEnd"`
	PeriodStart    NullableDate     `json:"periodStart"`
	Sources        []BalanceSource  `json:"sources"`
	Timestamp      NullableDateTime `json:"timestamp"`
	Totals         Totals           `json:"totals"`
}

// BalanceSource When no eligible snapshot exists, snapshotId and fetchedAt are null and all totals fields are null. fetchedAt is when the source data was fetched.
type BalanceSource struct {
	FetchedAt  NullableDateTime `json:"fetchedAt"`
	SnapshotId NullableString   `json:"snapshotId"`
	Source     Source           `json:"source"`

	// Totals valuationJpy maps SBI grand_total_jpy / NRKN grand_total_jpy. costJpy and unrealizedPnlJpy map only NRKN total_cost_jpy and pnl_jpy; SBI values are null. Aggregate each field independently and return null if any requested source lacks that metric. Never infer a missing value.
	Totals Totals `json:"totals"`
}

// DecimalString Decimal number encoded as a string. Examples are hand-written synthetic values.
type DecimalString = string

// Detail defines model for Detail.
type Detail struct {
	Id              int                `json:"id"`
	ImportDate      *time.Time         `json:"importDate,omitempty"`
	ImportJudgeDate *time.Time         `json:"importJudgeDate,omitempty"`
	Name            string             `json:"name"`
	Price           int                `json:"price"`
	RegistDate      time.Time          `json:"registDate"`
	UseDate         openapi_types.Date `json:"useDate"`
}

// DetailsCount defines model for DetailsCount.
type DetailsCount struct {
	// Count total number of details
	Count int `json:"count"`
}

// Holding holdingId identifies a record within its immutable snapshot, not a product across time. Use compositeFigi to group the same identified product across snapshots or sources; use the parent snapshot's source and this holding's section as additional grouping dimensions when separate holdings are desired. When FIGI is absent, productCode can identify products within the same source only; names must not be used as product identifiers. Missing/unavailable values are null; no values are guessed. valuationJpy maps value_jpy and unrealizedPnlJpy maps pnl_jpy in both sources. costJpy maps NRKN cost_jpy; SBI holding costJpy is calculated as valuationJpy minus unrealizedPnlJpy, using exact decimal arithmetic on the stored JPY values in this snapshot. Missing operands produce null. This calculation is performed only for response holdings, not stored back in the DB or used to infer snapshot totals. referenceDate maps NRKN reference_date and is null for SBI. section maps SBI section and is null for NRKN. productCode maps NRKN product_code and is null for SBI. Record IDs are opaque to clients.
type Holding struct {
	CompositeFigi NullableString `json:"compositeFigi"`

	// CostJpy NRKN は取り込み値。SBI の明細は評価額から評価損益を引いて計算により補完する。どちらかの値がなければ null。
	CostJpy          NullableDecimal `json:"costJpy"`
	HoldingId        string          `json:"holdingId"`
	Name             string          `json:"name"`
	ProductCode      NullableString  `json:"productCode"`
	Quantity         NullableDecimal `json:"quantity"`
	ReferenceDate    NullableDate    `json:"referenceDate"`
	Section          NullableString  `json:"section"`
	UnrealizedPnlJpy NullableDecimal `json:"unrealizedPnlJpy"`
	ValuationJpy     NullableDecimal `json:"valuationJpy"`
}

// NullableDate defines model for NullableDate.
type NullableDate = *string

// NullableDateTime defines model for NullableDateTime.
type NullableDateTime = *string

// NullableDecimal defines model for NullableDecimal.
type NullableDecimal = *string

// NullableString defines model for NullableString.
type NullableString = *string

// Rule defines model for Rule.
type Rule struct {
	// CategoryId Examples: 210
	CategoryId int `json:"categoryId"`
	ExactMatch int `json:"exactMatch"`

	// FieldName Examples: name
	FieldName string `json:"fieldName"`
	Id        int    `json:"id"`
	Value     string `json:"value"`
}

// RuleRequest defines model for RuleRequest.
type RuleRequest struct {
	CategoryId int `json:"categoryId"`
	ExactMatch int `json:"exactMatch"`

	// FieldName Examples: name
	FieldName string `json:"fieldName"`
	Value     string `json:"value"`
}

// SnapshotDetail defines model for SnapshotDetail.
type SnapshotDetail struct {
	// FetchedAt Time source data was fetched.
	FetchedAt time.Time `json:"fetchedAt"`
	Holdings  []Holding `json:"holdings"`

	// ImportedAt Time this snapshot was imported into the system.
	ImportedAt time.Time `json:"importedAt"`

	// SnapshotId Stable opaque globally unique ID for this immutable snapshot.
	SnapshotId string `json:"snapshotId"`
	Source     Source `json:"source"`

	// Totals valuationJpy maps SBI grand_total_jpy / NRKN grand_total_jpy. costJpy and unrealizedPnlJpy map only NRKN total_cost_jpy and pnl_jpy; SBI values are null. Aggregate each field independently and return null if any requested source lacks that metric. Never infer a missing value.
	Totals Totals `json:"totals"`
}

// SnapshotPage defines model for SnapshotPage.
type SnapshotPage struct {
	Items      []SnapshotDetail `json:"items"`
	NextCursor NullableString   `json:"nextCursor"`
}

// SnapshotSummary Source totals are represented as decimal strings; null means unavailable.
type SnapshotSummary struct {
	// FetchedAt Time source data was fetched.
	FetchedAt time.Time `json:"fetchedAt"`

	// ImportedAt Time this snapshot was imported into the system.
	ImportedAt time.Time `json:"importedAt"`

	// SnapshotId Stable opaque globally unique ID for this immutable snapshot.
	SnapshotId string `json:"snapshotId"`
	Source     Source `json:"source"`

	// Totals valuationJpy maps SBI grand_total_jpy / NRKN grand_total_jpy. costJpy and unrealizedPnlJpy map only NRKN total_cost_jpy and pnl_jpy; SBI values are null. Aggregate each field independently and return null if any requested source lacks that metric. Never infer a missing value.
	Totals Totals `json:"totals"`
}

// Source defines model for Source.
type Source string

// Totals valuationJpy maps SBI grand_total_jpy / NRKN grand_total_jpy. costJpy and unrealizedPnlJpy map only NRKN total_cost_jpy and pnl_jpy; SBI values are null. Aggregate each field independently and return null if any requested source lacks that metric. Never infer a missing value.
type Totals struct {
	CostJpy          NullableDecimal `json:"costJpy"`
	UnrealizedPnlJpy NullableDecimal `json:"unrealizedPnlJpy"`
	ValuationJpy     NullableDecimal `json:"valuationJpy"`
}

// Sources defines model for Sources.
type Sources = []string

// BadRequest defines model for BadRequest.
type BadRequest = ApiError

// InternalError defines model for InternalError.
type InternalError = ApiError

// NotFound defines model for NotFound.
type NotFound = ApiError

// GetDetailsParams defines parameters for GetDetails.
type GetDetailsParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Sort sort key (useDate|name|price|registDate|importJudgeDate|importDate)
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order sort order (asc|desc)
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// PatchDetailsIdParams defines parameters for PatchDetailsId.
type PatchDetailsIdParams struct {
	// Ope operate name ("reset": judge history reset)
	Ope string `form:"ope" json:"ope"`
}

// GetHealthTextBody defines parameters for GetHealth.
type GetHealthTextBody = string

// GetRulesParams defines parameters for GetRules.
type GetRulesParams struct {
	// Sort sort key (id|fieldName|value|exactMatch|categoryId)
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Order sort order (asc|desc)
	Order *string `form:"order,omitempty" json:"order,omitempty"`
}

// GetFinancialAssetBalancesParams defines parameters for GetFinancialAssetBalances.
type GetFinancialAssetBalancesParams struct {
	// Source Repeatable source filter. Omit to request both sources.
	Source *Sources `form:"source,omitempty" json:"source,omitempty"`

	// At RFC 3339 inclusive cutoff; mutually exclusive with from/to.
	At *time.Time `form:"at,omitempty" json:"at,omitempty"`

	// From Inclusive calendar date in Asia/Tokyo; requires to.
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive calendar date in Asia/Tokyo; requires from.
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Interval Range mode only; day or month.
	Interval *GetFinancialAssetBalancesParamsInterval `form:"interval,omitempty" json:"interval,omitempty"`

	// Limit Range mode only; page size must match when continuing a cursor.
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Range mode only; opaque cursor from the previous page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// GetFinancialAssetBalancesParamsSource defines parameters for GetFinancialAssetBalances.
type GetFinancialAssetBalancesParamsSource string

// GetFinancialAssetBalancesParamsInterval defines parameters for GetFinancialAssetBalances.
type GetFinancialAssetBalancesParamsInterval string

// ListFinancialAssetSnapshotsParams defines parameters for ListFinancialAssetSnapshots.
type ListFinancialAssetSnapshotsParams struct {
	// Source Repeatable source filter. Omit to request both sources.
	Source *Sources `form:"source,omitempty" json:"source,omitempty"`

	// From Inclusive fetchedAt boundary, RFC 3339 with timezone.
	From *time.Time `form:"from,omitempty" json:"from,omitempty"`

	// To Exclusive fetchedAt boundary, RFC 3339 with timezone.
	To    *time.Time `form:"to,omitempty" json:"to,omitempty"`
	Limit *int       `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque cursor returned by the previous page.
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListFinancialAssetSnapshotsParamsSource defines parameters for ListFinancialAssetSnapshots.
type ListFinancialAssetSnapshotsParamsSource string

// GetHealthTextRequestBody defines body for GetHealth for text/plain ContentType.
type GetHealthTextRequestBody = GetHealthTextBody

// PostRulesJSONRequestBody defines body for PostRules for application/json ContentType.
type PostRulesJSONRequestBody = RuleRequest
