// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Detail defines model for Detail.
type Detail struct {
	Id              int                `json:"id"`
	ImportDate      *time.Time         `json:"importDate,omitempty"`
	ImportJudgeDate *time.Time         `json:"importJudgeDate,omitempty"`
	Name            string             `json:"name"`
	Price           int                `json:"price"`
	RegistDate      time.Time          `json:"registDate"`
	UseDate         openapi_types.Date `json:"useDate"`
}

// GetHealthTextBody defines parameters for GetHealth.
type GetHealthTextBody = string

// GetDetailsParams defines parameters for GetDetails.
type GetDetailsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetHealthTextRequestBody defines body for GetHealth for text/plain ContentType.
type GetHealthTextRequestBody = GetHealthTextBody
