// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package openapi

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Import defines model for Import.
type Import struct {
	Id              float32            `json:"id"`
	ImportDate      *time.Time         `json:"importDate,omitempty"`
	ImportJudgeDate *time.Time         `json:"importJudgeDate,omitempty"`
	Name            string             `json:"name"`
	RegistDate      time.Time          `json:"registDate"`
	UseDate         openapi_types.Date `json:"useDate"`
}

// GetImportsParams defines parameters for GetImports.
type GetImportsParams struct {
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}
