version: '3'
services:
  # mf-importer-lastmonth:
  #   image: mf-importer
  #   container_name: mf-importer-lastmonth
  #   command: [ "cf", "--lastmonth", "True" ]
  #   volumes:
  #     - ./:/data/
  #   depends_on:
  #     - mf-importer-db
  #   environment:
  #     - db_pass=pass

  mf-importer-db:
    image: mariadb:10.9
    container_name: mf-importer-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mfimporter
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
