services:
  mf-importer-db:
    image: mariadb:10
    container_name: mf-importer-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mfimporter
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
  mf-importer-api:
    image: mf-importer-api
    container_name: mf-importer-api
    ports:
      - "8080:8080"
    environment:
    - DB_HOST=mf-importer-db
