version: '3'
services:
  mf-importer-dev:
    build:
      dockerfile: ./Dockerfile
    container_name: mf-importer-dev
    command: [ "sleep", "infinity" ]
    volumes:
      - ../../mf-importer:/workspace/mf-importer
    environment:
      - db_host=mf-importer-db
      - db_pass=password

  mf-importer-db:
    image: mariadb:10.9
    container_name: mf-importer-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mfimporter
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
      - TZ=Asia/Tokyo
