-- +migrate Up
ALTER TABLE `sbi_snapshot`
    MODIFY `fetched_at` DATETIME(6) NOT NULL COMMENT 'Assets.fetched_at (Asia/Tokyo wall-clock, truncated to microseconds)',
    MODIFY `grand_total_jpy` DECIMAL(14,2) NULL COMMENT 'grand_total_jpy = nisa+old_nisa+cash+others; NULL when incomplete',
    MODIFY `nisa_total_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.total_jpy',
    MODIFY `nisa_prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.prev_day_jpy',
    MODIFY `nisa_prev_day_pct` DECIMAL(10,4) NULL COMMENT 'nisa.prev_day_pct',
    MODIFY `nisa_prev_month_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.prev_month_jpy',
    MODIFY `nisa_prev_month_pct` DECIMAL(10,4) NULL COMMENT 'nisa.prev_month_pct',
    MODIFY `nisa_pnl_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.pnl_jpy (評価損益)',
    MODIFY `nisa_pnl_pct` DECIMAL(10,4) NULL COMMENT 'nisa.pnl_pct',
    MODIFY `nisa_domestic_value_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.domestic_stocks.value_jpy',
    MODIFY `nisa_domestic_pnl_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.domestic_stocks.pnl_jpy',
    MODIFY `nisa_domestic_pnl_pct` DECIMAL(10,4) NULL COMMENT 'nisa.domestic_stocks.pnl_pct',
    MODIFY `nisa_domestic_prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.domestic_stocks.prev_day_jpy',
    MODIFY `nisa_domestic_prev_day_pct` DECIMAL(10,4) NULL COMMENT 'nisa.domestic_stocks.prev_day_pct',
    MODIFY `nisa_domestic_prev_month_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.domestic_stocks.prev_month_jpy',
    MODIFY `nisa_domestic_prev_month_pct` DECIMAL(10,4) NULL COMMENT 'nisa.domestic_stocks.prev_month_pct',
    MODIFY `nisa_us_value_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.us_stocks.value_jpy',
    MODIFY `nisa_us_pnl_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.us_stocks.pnl_jpy',
    MODIFY `nisa_us_pnl_pct` DECIMAL(10,4) NULL COMMENT 'nisa.us_stocks.pnl_pct',
    MODIFY `nisa_us_prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.us_stocks.prev_day_jpy',
    MODIFY `nisa_us_prev_day_pct` DECIMAL(10,4) NULL COMMENT 'nisa.us_stocks.prev_day_pct',
    MODIFY `nisa_us_prev_month_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.us_stocks.prev_month_jpy',
    MODIFY `nisa_us_prev_month_pct` DECIMAL(10,4) NULL COMMENT 'nisa.us_stocks.prev_month_pct',
    MODIFY `nisa_funds_value_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.funds.value_jpy',
    MODIFY `nisa_funds_pnl_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.funds.pnl_jpy',
    MODIFY `nisa_funds_pnl_pct` DECIMAL(10,4) NULL COMMENT 'nisa.funds.pnl_pct',
    MODIFY `nisa_funds_prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.funds.prev_day_jpy',
    MODIFY `nisa_funds_prev_day_pct` DECIMAL(10,4) NULL COMMENT 'nisa.funds.prev_day_pct',
    MODIFY `nisa_funds_prev_month_jpy` DECIMAL(14,2) NULL COMMENT 'nisa.funds.prev_month_jpy',
    MODIFY `nisa_funds_prev_month_pct` DECIMAL(10,4) NULL COMMENT 'nisa.funds.prev_month_pct',
    MODIFY `old_nisa_total_jpy` DECIMAL(14,2) NULL COMMENT 'old_nisa.total_jpy',
    MODIFY `old_nisa_prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'old_nisa.prev_day_jpy',
    MODIFY `old_nisa_prev_day_pct` DECIMAL(10,4) NULL COMMENT 'old_nisa.prev_day_pct',
    MODIFY `old_nisa_pnl_jpy` DECIMAL(14,2) NULL COMMENT 'old_nisa.pnl_jpy',
    MODIFY `old_nisa_pnl_pct` DECIMAL(10,4) NULL COMMENT 'old_nisa.pnl_pct',
    MODIFY `cash_jpy_amount` DECIMAL(14,2) NULL COMMENT 'cash.jpy.amount (== value_jpy for JPY)',
    MODIFY `cash_jpy_value_jpy` DECIMAL(14,2) NULL COMMENT 'cash.jpy.value_jpy',
    MODIFY `cash_usd_amount` DECIMAL(14,4) NULL COMMENT 'cash.usd.amount (USD)',
    MODIFY `cash_usd_value_jpy` DECIMAL(14,2) NULL COMMENT 'cash.usd.value_jpy (JPY converted)',
    MODIFY `other_funds_amount` DECIMAL(14,2) NULL COMMENT 'others.funds.amount',
    MODIFY `other_funds_value_jpy` DECIMAL(14,2) NULL COMMENT 'others.funds.value_jpy';

ALTER TABLE `sbi_holding`
    MODIFY `prev_day_jpy` DECIMAL(14,2) NULL COMMENT 'Holding.prev_day_jpy (per-unit JPY change; per 10k units for funds; NULL when unavailable)',
    MODIFY `prev_day_pct` DECIMAL(10,4) NULL COMMENT 'Holding.prev_day_pct (NULL when unavailable)';

UPDATE `sbi_snapshot`
SET `grand_total_jpy` = NULL,
    `nisa_total_jpy` = NULL,
    `nisa_prev_day_jpy` = NULL,
    `nisa_prev_day_pct` = NULL,
    `nisa_prev_month_jpy` = NULL,
    `nisa_prev_month_pct` = NULL,
    `nisa_pnl_jpy` = NULL,
    `nisa_pnl_pct` = NULL,
    `nisa_domestic_value_jpy` = NULL,
    `nisa_domestic_pnl_jpy` = NULL,
    `nisa_domestic_pnl_pct` = NULL,
    `nisa_domestic_prev_day_jpy` = NULL,
    `nisa_domestic_prev_day_pct` = NULL,
    `nisa_domestic_prev_month_jpy` = NULL,
    `nisa_domestic_prev_month_pct` = NULL,
    `nisa_us_value_jpy` = NULL,
    `nisa_us_pnl_jpy` = NULL,
    `nisa_us_pnl_pct` = NULL,
    `nisa_us_prev_day_jpy` = NULL,
    `nisa_us_prev_day_pct` = NULL,
    `nisa_us_prev_month_jpy` = NULL,
    `nisa_us_prev_month_pct` = NULL,
    `nisa_funds_value_jpy` = NULL,
    `nisa_funds_pnl_jpy` = NULL,
    `nisa_funds_pnl_pct` = NULL,
    `nisa_funds_prev_day_jpy` = NULL,
    `nisa_funds_prev_day_pct` = NULL,
    `nisa_funds_prev_month_jpy` = NULL,
    `nisa_funds_prev_month_pct` = NULL,
    `old_nisa_total_jpy` = NULL,
    `old_nisa_prev_day_jpy` = NULL,
    `old_nisa_prev_day_pct` = NULL,
    `old_nisa_pnl_jpy` = NULL,
    `old_nisa_pnl_pct` = NULL,
    `cash_jpy_amount` = NULL,
    `cash_jpy_value_jpy` = NULL,
    `cash_usd_amount` = NULL,
    `cash_usd_value_jpy` = NULL,
    `other_funds_amount` = NULL,
    `other_funds_value_jpy` = NULL
WHERE `status` IN ('MAINTENANCE', 'ERROR');

UPDATE `sbi_holding`
SET `prev_day_jpy` = NULL,
    `prev_day_pct` = NULL
WHERE `section` = 'nisa_us';

-- +migrate Down
UPDATE `sbi_snapshot`
SET `grand_total_jpy` = COALESCE(`grand_total_jpy`, 0),
    `nisa_total_jpy` = COALESCE(`nisa_total_jpy`, 0),
    `nisa_prev_day_jpy` = COALESCE(`nisa_prev_day_jpy`, 0),
    `nisa_prev_day_pct` = COALESCE(`nisa_prev_day_pct`, 0),
    `nisa_prev_month_jpy` = COALESCE(`nisa_prev_month_jpy`, 0),
    `nisa_prev_month_pct` = COALESCE(`nisa_prev_month_pct`, 0),
    `nisa_pnl_jpy` = COALESCE(`nisa_pnl_jpy`, 0),
    `nisa_pnl_pct` = COALESCE(`nisa_pnl_pct`, 0),
    `nisa_domestic_value_jpy` = COALESCE(`nisa_domestic_value_jpy`, 0),
    `nisa_domestic_pnl_jpy` = COALESCE(`nisa_domestic_pnl_jpy`, 0),
    `nisa_domestic_pnl_pct` = COALESCE(`nisa_domestic_pnl_pct`, 0),
    `nisa_domestic_prev_day_jpy` = COALESCE(`nisa_domestic_prev_day_jpy`, 0),
    `nisa_domestic_prev_day_pct` = COALESCE(`nisa_domestic_prev_day_pct`, 0),
    `nisa_domestic_prev_month_jpy` = COALESCE(`nisa_domestic_prev_month_jpy`, 0),
    `nisa_domestic_prev_month_pct` = COALESCE(`nisa_domestic_prev_month_pct`, 0),
    `nisa_us_value_jpy` = COALESCE(`nisa_us_value_jpy`, 0),
    `nisa_us_pnl_jpy` = COALESCE(`nisa_us_pnl_jpy`, 0),
    `nisa_us_pnl_pct` = COALESCE(`nisa_us_pnl_pct`, 0),
    `nisa_us_prev_day_jpy` = COALESCE(`nisa_us_prev_day_jpy`, 0),
    `nisa_us_prev_day_pct` = COALESCE(`nisa_us_prev_day_pct`, 0),
    `nisa_us_prev_month_jpy` = COALESCE(`nisa_us_prev_month_jpy`, 0),
    `nisa_us_prev_month_pct` = COALESCE(`nisa_us_prev_month_pct`, 0),
    `nisa_funds_value_jpy` = COALESCE(`nisa_funds_value_jpy`, 0),
    `nisa_funds_pnl_jpy` = COALESCE(`nisa_funds_pnl_jpy`, 0),
    `nisa_funds_pnl_pct` = COALESCE(`nisa_funds_pnl_pct`, 0),
    `nisa_funds_prev_day_jpy` = COALESCE(`nisa_funds_prev_day_jpy`, 0),
    `nisa_funds_prev_day_pct` = COALESCE(`nisa_funds_prev_day_pct`, 0),
    `nisa_funds_prev_month_jpy` = COALESCE(`nisa_funds_prev_month_jpy`, 0),
    `nisa_funds_prev_month_pct` = COALESCE(`nisa_funds_prev_month_pct`, 0),
    `old_nisa_total_jpy` = COALESCE(`old_nisa_total_jpy`, 0),
    `old_nisa_prev_day_jpy` = COALESCE(`old_nisa_prev_day_jpy`, 0),
    `old_nisa_prev_day_pct` = COALESCE(`old_nisa_prev_day_pct`, 0),
    `old_nisa_pnl_jpy` = COALESCE(`old_nisa_pnl_jpy`, 0),
    `old_nisa_pnl_pct` = COALESCE(`old_nisa_pnl_pct`, 0),
    `cash_jpy_amount` = COALESCE(`cash_jpy_amount`, 0),
    `cash_jpy_value_jpy` = COALESCE(`cash_jpy_value_jpy`, 0),
    `cash_usd_amount` = COALESCE(`cash_usd_amount`, 0),
    `cash_usd_value_jpy` = COALESCE(`cash_usd_value_jpy`, 0),
    `other_funds_amount` = COALESCE(`other_funds_amount`, 0),
    `other_funds_value_jpy` = COALESCE(`other_funds_value_jpy`, 0);

UPDATE `sbi_holding`
SET `prev_day_jpy` = COALESCE(`prev_day_jpy`, 0),
    `prev_day_pct` = COALESCE(`prev_day_pct`, 0);

ALTER TABLE `sbi_snapshot`
    MODIFY `fetched_at` DATETIME(6) NOT NULL COMMENT 'Assets.fetched_at (UTC, nanoseconds preserved)',
    MODIFY `grand_total_jpy` DECIMAL(14,2) NOT NULL COMMENT 'grand_total_jpy = nisa+old_nisa+cash+others',
    MODIFY `nisa_total_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.total_jpy',
    MODIFY `nisa_prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.prev_day_jpy',
    MODIFY `nisa_prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.prev_day_pct',
    MODIFY `nisa_prev_month_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.prev_month_jpy',
    MODIFY `nisa_prev_month_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.prev_month_pct',
    MODIFY `nisa_pnl_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.pnl_jpy (評価損益)',
    MODIFY `nisa_pnl_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.pnl_pct',
    MODIFY `nisa_domestic_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.domestic_stocks.value_jpy',
    MODIFY `nisa_domestic_pnl_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.domestic_stocks.pnl_jpy',
    MODIFY `nisa_domestic_pnl_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.domestic_stocks.pnl_pct',
    MODIFY `nisa_domestic_prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.domestic_stocks.prev_day_jpy',
    MODIFY `nisa_domestic_prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.domestic_stocks.prev_day_pct',
    MODIFY `nisa_domestic_prev_month_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.domestic_stocks.prev_month_jpy',
    MODIFY `nisa_domestic_prev_month_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.domestic_stocks.prev_month_pct',
    MODIFY `nisa_us_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.us_stocks.value_jpy',
    MODIFY `nisa_us_pnl_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.us_stocks.pnl_jpy',
    MODIFY `nisa_us_pnl_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.us_stocks.pnl_pct',
    MODIFY `nisa_us_prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.us_stocks.prev_day_jpy (0 for US, no prev-day on foreign page)',
    MODIFY `nisa_us_prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.us_stocks.prev_day_pct',
    MODIFY `nisa_us_prev_month_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.us_stocks.prev_month_jpy',
    MODIFY `nisa_us_prev_month_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.us_stocks.prev_month_pct',
    MODIFY `nisa_funds_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.funds.value_jpy',
    MODIFY `nisa_funds_pnl_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.funds.pnl_jpy',
    MODIFY `nisa_funds_pnl_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.funds.pnl_pct',
    MODIFY `nisa_funds_prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.funds.prev_day_jpy',
    MODIFY `nisa_funds_prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.funds.prev_day_pct',
    MODIFY `nisa_funds_prev_month_jpy` DECIMAL(14,2) NOT NULL COMMENT 'nisa.funds.prev_month_jpy',
    MODIFY `nisa_funds_prev_month_pct` DECIMAL(10,4) NOT NULL COMMENT 'nisa.funds.prev_month_pct',
    MODIFY `old_nisa_total_jpy` DECIMAL(14,2) NOT NULL COMMENT 'old_nisa.total_jpy',
    MODIFY `old_nisa_prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'old_nisa.prev_day_jpy',
    MODIFY `old_nisa_prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'old_nisa.prev_day_pct',
    MODIFY `old_nisa_pnl_jpy` DECIMAL(14,2) NOT NULL COMMENT 'old_nisa.pnl_jpy',
    MODIFY `old_nisa_pnl_pct` DECIMAL(10,4) NOT NULL COMMENT 'old_nisa.pnl_pct',
    MODIFY `cash_jpy_amount` DECIMAL(14,2) NOT NULL COMMENT 'cash.jpy.amount (== value_jpy for JPY)',
    MODIFY `cash_jpy_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'cash.jpy.value_jpy',
    MODIFY `cash_usd_amount` DECIMAL(14,4) NOT NULL COMMENT 'cash.usd.amount (USD)',
    MODIFY `cash_usd_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'cash.usd.value_jpy (JPY converted)',
    MODIFY `other_funds_amount` DECIMAL(14,2) NOT NULL COMMENT 'others.funds.amount',
    MODIFY `other_funds_value_jpy` DECIMAL(14,2) NOT NULL COMMENT 'others.funds.value_jpy';

ALTER TABLE `sbi_holding`
    MODIFY `prev_day_jpy` DECIMAL(14,2) NOT NULL COMMENT 'Holding.prev_day_jpy (前日比円, 0 if unavailable for US)',
    MODIFY `prev_day_pct` DECIMAL(10,4) NOT NULL COMMENT 'Holding.prev_day_pct (前日比%)';
