name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  frontend-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker image build
        run: docker build -t mf-importer-fe -f build/fe/Dockerfile .
