name: pytest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
        - "**"

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.9 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      # - name: sql-migration install
      #   run: go install github.com/rubenv/sql-migrate/...@latest
      - name: Wait for ready DB
        run: |
          until mysql -u root -ppassword -h 127.0.0.1 -e '\q'; do sleep 1; done
          echo "MariaDB is up!"
      - name: migration
        run: make migration
      - name: Setup python module
        run: pip install -r build/requirements.txt
      - name: Run Tests
        run: make pytest

    services:
      db:
        image: mariadb:10.9
        ports:
          - 3306:3306
        env: 
          MYSQL_DATABASE: mfimporter
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USER: user
          MYSQL_PASSWORD: pwd
          TZ: Asia/Tokyo
