name: IntTest

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  db-migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22

      - name: Build
        run: make bin

      - name: Ready for MariaDB
        run: until mysql -u root -ppassword -h 127.0.0.1 -e '\q'; do sleep 1; done  # DBが起動して応答できるまで待つ

      - name: Migration
        run: make migration

      - name: Migration Down
        run: |
          cd migration; \
          ${SQL_MIGRATE_BIN} down -limit=0 -env=local;
        env:
          SQL_MIGRATE_BIN: "../vendor_ci/sql-migrate"

    services:
      mariadb:
        image: mariadb:11
        ports:
          - "3306:3306"
        env:
          MYSQL_DATABASE: mfimporter
          MYSQL_ROOT_PASSWORD: password
          TZ: Asia/Tokyo
